apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: marciopedrocomba/gitopsfc
  newTag: d690a325a2988b2123b299193eede8d262ee809e
